name: Example VSIX Build

on:
  push:
    branches:
    - main
    paths: 
      - '**'
      - '!.editorconfig'
      - '!.gitattributes'
      - '!.gitignore'
      - '!*.md'
      - '!LICENSE'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  
jobs: 
  Build:
    name: Example Action  
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2    

    - name: Show Visual Studio locator information
      run: vswhere.exe

    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      
    - uses: microcompiler/install-vsix@main
      with: 
        packagename: 'nanoframework.nanoFramework-VS2019-Extension'
          
